language: python
python:
    - 3.4
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install coveralls
script:
  - nostests --with-coverage
after_success:
  - coveralls
